module.exports = {
  profile: require('./parser/profil.js'),
  agliste: require('./parser/agliste.js'),
  live: require('./parser/live.js'),
  indizes: require('./parser/indizes.js'),
  chronik: require('./parser/chronik.js'),
  depot: require('./parser/depot.js'),
  aktionaere: require('./parser/aktionaere.js'),
  kontoauszug: require('./parser/kontoauszug.js'),
  kaeufer: require('./parser/kaeufer.js'),
  orderbuch: require('./parser/orderbuch.js'),
  trades: require('./parser/trades.js'),
  online: require('./parser/online.js'),
  bilanzen: require('./parser/bilanzen.js'),
  index: require('./parser/index.js'),
};
